### ISSUE TITLE
Resilient against Database Corruption

### ISSUE THREAD

**Issue by xloem** [Qoracoin/Qora#37] opened 2016-01-31 10:10 UTC
My client stopped functioning properly when my database became corrupted.  I don't know how it happened, perhaps a crash at a poor time.  It was detectable in that the database code was throwing an error.

Seems to me a well-behaving client would recreate the database in such a scenario.  But it would want to preserve any recoverable unconfirmed transactions.

**Comment by catbref** [comment] 2018-03-08 14:39
There was a race condition in v0.26.0 where two threads were both trying to access then shutdown the database at the same time.

Can you update your client to the latest v0.26.6 (or wait for v0.26.7 if you experience some network issues which should be coming out soon).

Backups of the database are created every so often and recovery should be automatic.

Unconfirmed transactions are part of the database and could potentially be lost if there's some catastrophic failure. However they are also broadcast to peers and so transmitted back to your node at some point.

Going to close this issue due to significant code change since Jan 2016.
If anyone experiences catastrophic database corruption with v0.26.6 onwards, please open a fresh ticket (with logfiles!)

**Closed by catbref** 2018-03-08 14:39 UTC
