### ISSUE TITLE
java.io.IOError: java.nio.channels.ClosedChannelException

### ISSUE THREAD

**Issue by agran** [Qoracoin/Qora#56] opened 2016-03-22 14:30 UTC
> INFO: Connection successfull : /60.29.233.154
> Exception in thread "Thread-24" java.io.IOError: java.nio.channels.ClosedChannelException
>         at org.mapdb.Volume$MappedFileVol.makeNewBuffer(Volume.java:632)
>         at org.mapdb.Volume$ByteBufferVol.tryAvailable(Volume.java:375)
>         at org.mapdb.Volume.ensureAvailable(Volume.java:67)
>         at org.mapdb.StoreWAL.logAllocate(StoreWAL.java:299)
>         at org.mapdb.StoreWAL.update(StoreWAL.java:406)
>         at org.mapdb.Caches$HashTable.update(Caches.java:270)
>         at org.mapdb.EngineWrapper.update(EngineWrapper.java:63)
>         at org.mapdb.BTreeMap.put2(BTreeMap.java:707)
>         at org.mapdb.BTreeMap.put(BTreeMap.java:643)
>         at database.PeerMap.addPeer(PeerMap.java:441)
>         at network.PeerManager.addPeer(PeerManager.java:51)
>         at network.Network.onConnect(Network.java:71)
>         at network.Peer.connect(Peer.java:137)
>         at network.ConnectionCreator.run(ConnectionCreator.java:118)
> Caused by: java.nio.channels.ClosedChannelException
>         at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:110)
>         at sun.nio.ch.FileChannelImpl.size(FileChannelImpl.java:300)
>         at org.mapdb.Volume$MappedFileVol.makeNewBuffer(Volume.java:604)
>         ... 13 more
> мар 20, 2016 7:27:29 PM network.Network onDisconnect
> INFO: Connection close : /203.217.62.44
> мар 20, 2016 7:27:29 PM network.Network onDisconnect
> INFO: Connection close : /203.217.62.44
> мар 20, 2016 7:27:39 PM network.Network onDisconnect
> INFO: Connection close : /60.29.233.154
> мар 20, 2016 7:27:39 PM network.Network onDisconnect
> INFO: Connection close : /60.29.233.154
> мар 20, 2016 7:33:15 PM ntp.NTP getTime
> INFO: Adjusting time with -105300 milliseconds.
> мар 20, 2016 7:33:15 PM network.Network onDisconnect
> INFO: Connection close : /2.95.31.184
> Exception in thread "Thread-123018" java.io.IOError: java.nio.channels.ClosedChannelException
>         at org.mapdb.Volume$MappedFileVol.makeNewBuffer(Volume.java:632)
>         at org.mapdb.Volume$ByteBufferVol.tryAvailable(Volume.java:375)
>         at org.mapdb.Volume.ensureAvailable(Volume.java:67)
>         at org.mapdb.StoreWAL.logAllocate(StoreWAL.java:299)
>         at org.mapdb.StoreWAL.update(StoreWAL.java:406)
>         at org.mapdb.Caches$HashTable.update(Caches.java:270)
>         at org.mapdb.EngineWrapper.update(EngineWrapper.java:63)
>         at org.mapdb.BTreeMap.put2(BTreeMap.java:746)
>         at org.mapdb.BTreeMap.put(BTreeMap.java:643)
>         at database.DBMap.set(DBMap.java:139)
>         at database.TransactionMap.add(TransactionMap.java:124)
>         at qora.BlockGenerator.addUnconfirmedTransaction(BlockGenerator.java:123)
>         at qora.BlockGenerator.addUnconfirmedTransaction(BlockGenerator.java:117)
>         at controller.Controller.onMessage(Controller.java:920)
>         at network.Network.onMessage(Network.java:265)
>         at network.Peer.run(Peer.java:174)
> Caused by: java.nio.channels.ClosedChannelException
>         at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:110)
>         at sun.nio.ch.FileChannelImpl.size(FileChannelImpl.java:300)
>         at org.mapdb.Volume$MappedFileVol.makeNewBuffer(Volume.java:604)
>         ... 15 more
> мар 20, 2016 7:45:06 PM ntp.NTP getTime
> INFO: Adjusting time with -105300 milliseconds.
> мар 20, 2016 7:46:06 PM network.Network onDisconnect
> INFO: Connection close : /80.187.102.188
> мар 20, 2016 8:08:41 PM ntp.NTP getTime
> INFO: Adjusting time with -105300 milliseconds.
> мар 20, 2016 8:31:49 PM network.Network onDisconnect
> INFO: Connection close : /85.212.14.117
> мар 20, 2016 9:00:33 PM network.Network onDisconnect

error from my node mirror.qora.co.in after weeks of work

https://github.com/jankotek/MapDB/issues/384

**Comment by agran** [comment] 2016-03-27 23:29
2016-03-27 16:08:40 INFO  Network:66 - Connection successfull : /60.29.233.154
Exception in thread "Thread-24" java.io.IOError: java.nio.channels.ClosedChannelException
        at org.mapdb.Volume$MappedFileVol.makeNewBuffer(Volume.java:632)
        at org.mapdb.Volume$ByteBufferVol.tryAvailable(Volume.java:375)
        at org.mapdb.Volume.ensureAvailable(Volume.java:67)
        at org.mapdb.StoreWAL.logAllocate(StoreWAL.java:299)
        at org.mapdb.StoreWAL.update(StoreWAL.java:406)
        at org.mapdb.Caches$HashTable.update(Caches.java:270)
        at org.mapdb.EngineWrapper.update(EngineWrapper.java:63)
        at org.mapdb.BTreeMap.put2(BTreeMap.java:707)
        at org.mapdb.BTreeMap.put(BTreeMap.java:643)
        at database.PeerMap.addPeer(PeerMap.java:443)
        at network.PeerManager.addPeer(PeerManager.java:51)
        at network.Network.onConnect(Network.java:75)
        at network.Peer.connect(Peer.java:141)
        at network.ConnectionCreator.run(ConnectionCreator.java:67)
Caused by: java.nio.channels.ClosedChannelException
        at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:110)
        at sun.nio.ch.FileChannelImpl.size(FileChannelImpl.java:300)
        at org.mapdb.Volume$MappedFileVol.makeNewBuffer(Volume.java:604)
        ... 13 more
2016-03-27 16:08:50 INFO  Network:91 - Connection close : /60.29.233.154

**Comment by catbref** [comment] 2018-03-08 14:29
As this looks like a call to mapdb inside of Peer.run() maybe this is a duplicate of issue #69 
Closing as issue #69 has newer logfile dumps

**Closed by catbref** 2018-03-08 14:29 UTC
Labels: bug, duplicate, mapdb
